name: llm-nano-factory-runtime

services:
  llm-nano-factory-runtime:
    container_name: llm-nano-factory-runtime
    image: llm-nano-factory-runtime:latest
    build: .
    ipc: host
    restart: always
    ulimits:
      memlock: -1
      stack: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["4"]
              capabilities:
                - gpu
    volumes:
      - ${PWD}:/pwd
      - ${PWD}/jetbrains_gateway:/root/.cache/JetBrains
    ports:
      - "10022:10022"
    command: bash -c "service ssh start && tail -f /dev/null"

